name: Run backend tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend"

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "./backend/package-lock.json"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0

      - run: npm ci

      - run: npm test
        env:
          CI: true
          NODE_ENV: "testing"
          MONGODB_URI_DEV: ${{secrets.MONGODB_URI_DEV}}
