name: backend-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'backend'
    steps:
      - name: Deploy backend
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'
      - run: npm ci
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "backend"
        env:
          HD_VIMUTH: ${{secrets.VIMUTH}}
          HD_NODE_ENV: ${{secrets.NODE_ENV}}
          HD_MONGODB_URI_PROD: ${{secrets.MONGODB_URI_PROD}}
